"""Initial migration

Revision ID: 581dc55dba32
Revises: 
Create Date: 2025-12-17 10:09:58.627734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581dc55dba32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('daily_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nutrient_name', sa.String(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_nutrition_date'), 'daily_nutrition', ['date'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_id'), 'daily_nutrition', ['id'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_nutrient_name'), 'daily_nutrition', ['nutrient_name'], unique=False)
    op.create_index('ix_daily_nutrition_user_date_nutrient', 'daily_nutrition', ['user_id', 'date', 'nutrient_name'], unique=True)
    op.create_index(op.f('ix_daily_nutrition_user_id'), 'daily_nutrition', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'OTHER', name='mealtype'), nullable=False),
    sa.Column('source_type', sa.Enum('IMAGE', 'PDF', 'CSV', 'MANUAL', name='mealsource'), nullable=False),
    sa.Column('source_file_path', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meal_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_meal_date'), 'meals', ['meal_date'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.Enum('DEFICIENCY', 'EXCESS', 'IMBALANCE', 'ALLERGY', 'INTERACTION', name='risktype'), nullable=False),
    sa.Column('nutrient_name', sa.String(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_calculated_at'), 'risk_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_risk_scores_nutrient_name'), 'risk_scores', ['nutrient_name'], unique=False)
    op.create_index(op.f('ix_risk_scores_risk_level'), 'risk_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_scores_risk_type'), 'risk_scores', ['risk_type'], unique=False)
    op.create_index(op.f('ix_risk_scores_user_id'), 'risk_scores', ['user_id'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_barcode'), 'food_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_food_items_id'), 'food_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_items_meal_id'), 'food_items', ['meal_id'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.create_index(op.f('ix_food_items_normalized_name'), 'food_items', ['normalized_name'], unique=False)
    op.create_table('nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('per_100g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrients_food_item_id'), 'nutrients', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_nutrients_id'), 'nutrients', ['id'], unique=False)
    op.create_index(op.f('ix_nutrients_name'), 'nutrients', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrients_name'), table_name='nutrients')
    op.drop_index(op.f('ix_nutrients_id'), table_name='nutrients')
    op.drop_index(op.f('ix_nutrients_food_item_id'), table_name='nutrients')
    op.drop_table('nutrients')
    op.drop_index(op.f('ix_food_items_normalized_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_meal_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_barcode'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_risk_scores_user_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_risk_type'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_risk_level'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_nutrient_name'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_calculated_at'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_date'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_daily_nutrition_user_id'), table_name='daily_nutrition')
    op.drop_index('ix_daily_nutrition_user_date_nutrient', table_name='daily_nutrition')
    op.drop_index(op.f('ix_daily_nutrition_nutrient_name'), table_name='daily_nutrition')
    op.drop_index(op.f('ix_daily_nutrition_id'), table_name='daily_nutrition')
    op.drop_index(op.f('ix_daily_nutrition_date'), table_name='daily_nutrition')
    op.drop_table('daily_nutrition')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

